version: '3.8'

services:
  server:
    build: ./server
    networks:
      - appnet

  app:
    build: ./app
    networks:
      - appnet

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app
      - server
    networks:
      - appnet

networks:
  appnet:
