version: '3.8'

services:
  server:
    build: ./server
    networks:
      - appnet

  app:
    build: ./app
    networks:
      - appnet

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app
      - server
    networks:
      - appnet

  ngrok:
    build: ./ngrok
    depends_on:
      - nginx
    networks:
      - appnet
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_BASIC_AUTH_USER=${NGROK_BASIC_AUTH_USER}
      - NGROK_BASIC_AUTH_PASS=${NGROK_BASIC_AUTH_PASS}

networks:
  appnet:
